#!/bin/sh

# basic interfaces
sudo cp interfaces /etc/network/
sudo /etc/init.d/networking restart

# DHCP server
sudo cp dhcpd.conf /etc/dhcpd/
sudo /etc/init.d/isc-dhcp-server restart

# NAT routing
sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
sudo iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
# TODO: add more rules here for extra security...

sudo ifdown eth1 && sudo ifup eth1
sudo iptables-save > /etc/iptables.ip.rules

sudo cp iptables /etc/network/if-pre-up/
sudo chown root:root /etc/network/if-pre-up.d/iptables
sudo chmod 755 /etc/network/if-pre-up.d/iptables

# eof

